/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Principal.java
 *
 * Created on 21/01/2011, 07:34:43
 */
package br.com.eugeniosolucoes.view.forms;

import br.com.eugeniosolucoes.modelo.RpsConfig;
import br.com.eugeniosolucoes.service.NotaService;
import br.com.eugeniosolucoes.util.LocalStoreHelper;
import java.awt.Frame;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author eugenio
 */
public class ConfigEnvioDeRpsForm extends BaseDialog {

    private static final Logger LOG = LoggerFactory.getLogger( ConfigEnvioDeRpsForm.class );

    private RpsConfig obj;

    /**
     * Creates new dialog ConfigEnvioDeBoletoForm
     *
     * @param owner
     * @param title
     * @param modal
     */
    public ConfigEnvioDeRpsForm( Frame owner, String title, boolean modal ) {
        super( owner, title, modal );
        initComponents();
        obj = new RpsConfig();
        restaurarObjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabEmail = new javax.swing.JTabbedPane();
        painelEmail = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiscriminacao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração de Envio de Boletos");

        lblMensagem.setText("Discriminação do Serviço:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalvar);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtDiscriminacao.setColumns(20);
        txtDiscriminacao.setRows(5);
        jScrollPane1.setViewportView(txtDiscriminacao);

        javax.swing.GroupLayout painelEmailLayout = new javax.swing.GroupLayout(painelEmail);
        painelEmail.setLayout(painelEmailLayout);
        painelEmailLayout.setHorizontalGroup(
            painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelEmailLayout.createSequentialGroup()
                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEmailLayout.setVerticalGroup(
            painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabEmail.addTab("Dados do RPS", painelEmail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabEmail)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(565, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            obj = new RpsConfig();
            obj.setDiscriminacaoDoServico( txtDiscriminacao.getText() );
            LocalStoreHelper.save( obj, NotaService.RPS_CONFIG_FILE );
            this.dispose();
        } catch ( Exception ex ) {
            LOG.error( ex.getMessage(), ex );
            JOptionPane.showMessageDialog( null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE );

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void restaurarObjeto() {
        try {
            File file = new File( NotaService.RPS_CONFIG_FILE );
            if ( file.exists() ) {
                obj = (RpsConfig) LocalStoreHelper.restore( new FileInputStream( NotaService.RPS_CONFIG_FILE ) );
                txtDiscriminacao.setText( obj.getDiscriminacaoDoServico() );
            }
        } catch ( Exception ex ) {
            LOG.error( ex.getMessage(), ex );
            JOptionPane.showMessageDialog( null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE );
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JPanel painelEmail;
    private javax.swing.JTabbedPane tabEmail;
    private javax.swing.JTextArea txtDiscriminacao;
    // End of variables declaration//GEN-END:variables
}
