/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eugeniosolucoes.view.forms;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author eugenio
 */
public class MainForm extends BaseForm {

    static final Logger LOG = Logger.getLogger( MainForm.class.getName() );

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setup();
    }

    private void setup() {
        setExtendedState( MAXIMIZED_BOTH );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConteudo = new javax.swing.JPanel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuSecretaria = new javax.swing.JMenu();
        jMenuTesouraria = new javax.swing.JMenu();
        mItemEnvioBoletos = new javax.swing.JMenuItem();
        jMenuSistema = new javax.swing.JMenu();
        jMenuConfiguracoes = new javax.swing.JMenu();
        mItemConfigEnvioDeBoletos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpConteudoLayout = new javax.swing.GroupLayout(jpConteudo);
        jpConteudo.setLayout(jpConteudoLayout);
        jpConteudoLayout.setHorizontalGroup(
            jpConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpConteudoLayout.setVerticalGroup(
            jpConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        getContentPane().add(jpConteudo, java.awt.BorderLayout.CENTER);

        jMenuSecretaria.setText("Secretaria");
        jMenuBarMain.add(jMenuSecretaria);

        jMenuTesouraria.setText("Tesouraria");

        mItemEnvioBoletos.setText("Envio de Boletos");
        mItemEnvioBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemEnvioBoletosActionPerformed(evt);
            }
        });
        jMenuTesouraria.add(mItemEnvioBoletos);

        jMenuBarMain.add(jMenuTesouraria);

        jMenuSistema.setText("Sistema");

        jMenuConfiguracoes.setText("Configurações");

        mItemConfigEnvioDeBoletos.setText("Envio de Boletos...");
        mItemConfigEnvioDeBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemConfigEnvioDeBoletosActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(mItemConfigEnvioDeBoletos);

        jMenuSistema.add(jMenuConfiguracoes);
        jMenuSistema.add(jSeparator1);

        mItemSair.setText("Sair");
        mItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSairActionPerformed(evt);
            }
        });
        jMenuSistema.add(mItemSair);

        jMenuBarMain.add(jMenuSistema);

        setJMenuBar(jMenuBarMain);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSairActionPerformed
        System.exit( 0 );
    }//GEN-LAST:event_mItemSairActionPerformed

    private void mItemEnvioBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemEnvioBoletosActionPerformed
        new BoletoForm( this, "Envio de Boletos", true ).setVisible( true );
    }//GEN-LAST:event_mItemEnvioBoletosActionPerformed

    private void mItemConfigEnvioDeBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemConfigEnvioDeBoletosActionPerformed
        // TODO add your handling code here:
        new ConfigEnvioDeBoletoForm(this, "Configuração de Envio de Boletos", true ).setVisible( true );
    }//GEN-LAST:event_mItemConfigEnvioDeBoletosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenu jMenuSecretaria;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenu jMenuTesouraria;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel jpConteudo;
    private javax.swing.JMenuItem mItemConfigEnvioDeBoletos;
    private javax.swing.JMenuItem mItemEnvioBoletos;
    private javax.swing.JMenuItem mItemSair;
    // End of variables declaration//GEN-END:variables
}
