/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eugeniosolucoes.view.forms;

import br.com.eugeniosolucoes.service.NotaService;
import br.com.eugeniosolucoes.service.impl.NotaServiceImpl;
import br.com.eugeniosolucoes.util.RelatorioUtils;
import br.com.eugeniosolucoes.view.model.NotaCariocaModel;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import org.joda.time.LocalDate;
import org.slf4j.LoggerFactory;

/**
 *
 * @author eugenio
 */
public class NotaForm extends BaseDialog {

    private static final org.slf4j.Logger LOG = LoggerFactory.getLogger( NotaForm.class );

    private final NotaService notaService = new NotaServiceImpl();

    /**
     * Creates new form View1
     *
     * @param owner
     * @param title
     * @param modal
     */
    public NotaForm( Frame owner, String title, boolean modal ) {
        super( owner, title, modal );
        initComponents();
        jProgressBar1.setVisible( false );
    }

    public NotaForm( Frame owner, String title, boolean modal, int w, int h ) {
        super( owner, title, modal );
        initComponents();
        configCustomSize( w, h );
        jProgressBar1.setVisible( false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plConteudo = new javax.swing.JPanel();
        pnlListarRpsEnviados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdtPagamento = new com.toedter.calendar.JDateChooser( new java.util.Date() );
        btnEnviarLoteRps = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jdtEnvio = new com.toedter.calendar.JDateChooser(new java.util.Date());
        btnListarRpsEnviados = new javax.swing.JButton();
        btnExportarExcel = new javax.swing.JButton();
        plDados = new javax.swing.JPanel();
        splDados = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviar Lote RPS");
        setType(java.awt.Window.Type.POPUP);

        plConteudo.setBackground(java.awt.SystemColor.control);
        plConteudo.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlListarRpsEnviados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Data Pagamento:");
        pnlListarRpsEnviados.add(jLabel1);
        pnlListarRpsEnviados.add(jdtPagamento);

        btnEnviarLoteRps.setText("Enviar Lote RPS");
        btnEnviarLoteRps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarLoteRpsActionPerformed(evt);
            }
        });
        pnlListarRpsEnviados.add(btnEnviarLoteRps);

        jProgressBar1.setIndeterminate(true);
        pnlListarRpsEnviados.add(jProgressBar1);

        jLabel2.setText("Data Envio:");
        pnlListarRpsEnviados.add(jLabel2);
        pnlListarRpsEnviados.add(jdtEnvio);

        btnListarRpsEnviados.setText("Listar RPS Enviados");
        btnListarRpsEnviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRpsEnviadosActionPerformed(evt);
            }
        });
        pnlListarRpsEnviados.add(btnListarRpsEnviados);

        btnExportarExcel.setText("Exportar para Excel");
        btnExportarExcel.setEnabled(false);
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });
        pnlListarRpsEnviados.add(btnExportarExcel);

        plDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Boleto", "Nome", "Data Pagamento", "Total", "Protocolo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.setIntercellSpacing(new java.awt.Dimension(3, 3));
        tblDados.setRowHeight(22);
        tblDados.getTableHeader().setReorderingAllowed(false);
        splDados.setViewportView(tblDados);

        javax.swing.GroupLayout plDadosLayout = new javax.swing.GroupLayout(plDados);
        plDados.setLayout(plDadosLayout);
        plDadosLayout.setHorizontalGroup(
            plDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splDados, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                .addContainerGap())
        );
        plDadosLayout.setVerticalGroup(
            plDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splDados, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout plConteudoLayout = new javax.swing.GroupLayout(plConteudo);
        plConteudo.setLayout(plConteudoLayout);
        plConteudoLayout.setHorizontalGroup(
            plConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListarRpsEnviados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plConteudoLayout.setVerticalGroup(
            plConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListarRpsEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(plConteudo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarLoteRpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarLoteRpsActionPerformed
        new Thread( new Runnable() {
            @Override
            public void run() {
                if ( jdtPagamento.getDate() != null ) {
                    try {
                        Date date = jdtPagamento.getDate();
                        jProgressBar1.setVisible( true );
                        btnEnviarLoteRps.setEnabled( false );
                        btnListarRpsEnviados.setEnabled( false );
                        notaService.enviarNsfe( date );
                        jdtEnvio.setDate( LocalDate.now().toDate() );
                        listarRpsEnviados( jdtEnvio.getDate() );
                    } catch ( Exception ex ) {
                        JOptionPane.showMessageDialog( null, ex.getMessage() );
                    } finally {
                        jProgressBar1.setVisible( false );
                        btnEnviarLoteRps.setEnabled( true );
                        btnListarRpsEnviados.setEnabled( true );
                    }
                }
            }
        } ).start();
    }//GEN-LAST:event_btnEnviarLoteRpsActionPerformed

    private void btnListarRpsEnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRpsEnviadosActionPerformed
        // TODO add your handling code here:
        if ( jdtEnvio.getDate() != null ) {
            listarRpsEnviados( jdtEnvio.getDate() );
        }
    }//GEN-LAST:event_btnListarRpsEnviadosActionPerformed

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
        // TODO add your handling code here:
        FileOutputStream fs = null;
        BufferedOutputStream bs = null;
        final String relatorio = "relatorio-excel-envio-rps.xls";
        File file = new File( relatorio );
        try {
            List<NotaCariocaModel> dados = notaService.listarRpsEnviados( jdtEnvio.getDate() );
            byte[] arquivoExcel = RelatorioUtils.gerarArquivoExcel( "/templates/relatorio-excel-envio-rps.jasper",
                    dados, new HashMap<String, Object>() );
            fs = new FileOutputStream( file );
            bs = new BufferedOutputStream( fs );
            bs.write( arquivoExcel );
            bs.close();
        } catch ( Exception e ) {
            JOptionPane.showMessageDialog( null, e.getMessage() );
        } finally {
            try {
                if( bs != null ) bs.close();
                if( fs != null ) fs.close();
            } catch ( IOException ex ) {
                LOG.error( ex.getMessage(), ex);
            }
        }
        if ( file.exists() && file.canRead() ) {
            try {
                Desktop.getDesktop().open( file );
            } catch ( IOException ex ) {
                LOG.error( ex.getMessage(), ex);
            }
        }
    }//GEN-LAST:event_btnExportarExcelActionPerformed

    private void listarRpsEnviados( Date data ) throws HeadlessException {
        try {
            MainForm.setWaitCursor( this );
            List<NotaCariocaModel> dados = notaService.listarRpsEnviados( data );
            tblDados.setModel( new javax.swing.table.DefaultTableModel( getDados( dados ),
                    new String[]{"Boleto", "Nome", "Data Pagamento", "Total", "Protocolo"} ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
                };

                @Override
                public boolean isCellEditable( int rowIndex, int columnIndex ) {
                    return canEdit[columnIndex];
                }
            } );
            configurarTabela();
            btnExportarExcel.setEnabled( tblDados.getModel().getRowCount() > 0 );
            MainForm.setDefaultCursor( this );
        } catch ( Exception ex ) {
            JOptionPane.showMessageDialog( null, ex.getMessage() );
        }
    }

    private void configurarTabela() {
        tblDados.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );

        DefaultTableCellRenderer cellRight = new DefaultTableCellRenderer();
        cellRight.setHorizontalAlignment( SwingConstants.RIGHT );
        DefaultTableCellRenderer cellCenter = new DefaultTableCellRenderer();
        cellCenter.setHorizontalAlignment( SwingConstants.CENTER );

        tblDados.getColumnModel().getColumn( 0 ).setCellRenderer( cellCenter );
        tblDados.getColumnModel().getColumn( 2 ).setCellRenderer( cellCenter );
        tblDados.getColumnModel().getColumn( 3 ).setCellRenderer( cellCenter );
        tblDados.getColumnModel().getColumn( 4 ).setCellRenderer( cellRight );

        tblDados.getColumnModel().getColumn( 0 ).setPreferredWidth( 70 );
        tblDados.getColumnModel().getColumn( 1 ).setPreferredWidth( 350 );
        tblDados.getColumnModel().getColumn( 2 ).setPreferredWidth( 100 );
        tblDados.getColumnModel().getColumn( 3 ).setPreferredWidth( 80 );
        tblDados.getColumnModel().getColumn( 4 ).setPreferredWidth( 340 );

    }

    private Object[][] getDados( List<NotaCariocaModel> lista ) {
        Object[][] dados = new Object[lista.size()][];
        int i = 0;
        for ( NotaCariocaModel model : lista ) {
            dados[i] = new String[]{
                model.getNumeroBoleto(),
                model.getNome(),
                model.getDataPagamento(),
                model.getTotal(),
                model.getProtocolo()};
            i++;
        }
        return dados;
    }

    private void configCustomSize( int largura, int altura ) throws HeadlessException {
        this.setSize( largura, altura );
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( ( tela.width - getSize().width ) / 2, ( tela.height - getSize().height ) / 2,
                getSize().width, getSize().height );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarLoteRps;
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnListarRpsEnviados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private com.toedter.calendar.JDateChooser jdtEnvio;
    private com.toedter.calendar.JDateChooser jdtPagamento;
    private javax.swing.JPanel plConteudo;
    private javax.swing.JPanel plDados;
    private javax.swing.JPanel pnlListarRpsEnviados;
    private javax.swing.JScrollPane splDados;
    private javax.swing.JTable tblDados;
    // End of variables declaration//GEN-END:variables

}
