/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.eugeniosolucoes.view.forms;

import br.com.eugeniosolucoes.service.NotaService;
import br.com.eugeniosolucoes.service.impl.NotaServiceImpl;
import br.com.eugeniosolucoes.view.model.DadosBoletoModel;
import br.com.eugeniosolucoes.view.model.NotaCariocaModel;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eugenio
 */
public class NotaForm extends BaseDialog {

    static final Logger LOG = Logger.getLogger( NotaForm.class.getName() );

    private final NotaService notaService = new NotaServiceImpl();

    /**
     * Creates new form View1
     *
     * @param owner
     * @param title
     * @param modal
     */
    public NotaForm( Frame owner, String title, boolean modal ) {
        super( owner, title, modal );
        initComponents();
    }

    public NotaForm( Frame owner, String title, boolean modal, int w, int h ) {
        super( owner, title, modal );
        initComponents();
        configCustomSize( w, h );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plConteudo = new javax.swing.JPanel();
        pnlListarRpsEnviados = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser( new java.util.Date() );
        btnEnviarLoteRps = new javax.swing.JButton();
        btnListarRpsEnviados = new javax.swing.JButton();
        plDados = new javax.swing.JPanel();
        splDados = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enviar Lote RPS");
        setType(java.awt.Window.Type.POPUP);

        plConteudo.setBackground(java.awt.SystemColor.control);
        plConteudo.setPreferredSize(new java.awt.Dimension(800, 600));

        pnlListarRpsEnviados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlListarRpsEnviados.add(jDateChooser1);

        btnEnviarLoteRps.setText("Enviar Lote RPS");
        btnEnviarLoteRps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarLoteRpsActionPerformed(evt);
            }
        });
        pnlListarRpsEnviados.add(btnEnviarLoteRps);

        btnListarRpsEnviados.setText("Listar RPS Enviados");
        btnListarRpsEnviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRpsEnviadosActionPerformed(evt);
            }
        });
        pnlListarRpsEnviados.add(btnListarRpsEnviados);

        plDados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Boleto", "Nome", "Data Pagamento", "Total", "Protocolo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDados.setIntercellSpacing(new java.awt.Dimension(3, 3));
        tblDados.setRowHeight(22);
        tblDados.getTableHeader().setReorderingAllowed(false);
        splDados.setViewportView(tblDados);

        javax.swing.GroupLayout plDadosLayout = new javax.swing.GroupLayout(plDados);
        plDados.setLayout(plDadosLayout);
        plDadosLayout.setHorizontalGroup(
            plDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splDados, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                .addContainerGap())
        );
        plDadosLayout.setVerticalGroup(
            plDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splDados, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout plConteudoLayout = new javax.swing.GroupLayout(plConteudo);
        plConteudo.setLayout(plConteudoLayout);
        plConteudoLayout.setHorizontalGroup(
            plConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListarRpsEnviados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plConteudoLayout.setVerticalGroup(
            plConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plConteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListarRpsEnviados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(plConteudo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarLoteRpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarLoteRpsActionPerformed
        if ( jDateChooser1.getDate() != null ) {
            try {
                Date date = jDateChooser1.getDate();
                notaService.enviarNsfe( date );
                btnListarRpsEnviadosActionPerformed( evt );
            } catch ( Exception ex ) {
                JOptionPane.showMessageDialog( null, ex.getMessage() );
            }
        }
    }//GEN-LAST:event_btnEnviarLoteRpsActionPerformed

    private void btnListarRpsEnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRpsEnviadosActionPerformed
        // TODO add your handling code here:
        if ( jDateChooser1.getDate() != null ) {
            try {
                Date data = jDateChooser1.getDate();
                MainForm.setWaitCursor( this );
                List<NotaCariocaModel> dados = notaService.listarRspEnviados( data );
                tblDados.setModel( new javax.swing.table.DefaultTableModel( getDados( dados ),
                        new String[]{"Boleto", "Nome", "Data Pagamento", "Total", "Protocolo"} ) {
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false
                    };

                    @Override
                    public boolean isCellEditable( int rowIndex, int columnIndex ) {
                        return canEdit[columnIndex];
                    }
                } );
                configurarTabela();
                MainForm.setDefaultCursor( this );
            } catch ( Exception ex ) {
                JOptionPane.showMessageDialog( null, ex.getMessage() );
            }
        }
    }//GEN-LAST:event_btnListarRpsEnviadosActionPerformed
    
    private void configurarTabela() {
        tblDados.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );

        DefaultTableCellRenderer cellRight = new DefaultTableCellRenderer();
        cellRight.setHorizontalAlignment( SwingConstants.RIGHT );
        DefaultTableCellRenderer cellCenter = new DefaultTableCellRenderer();
        cellCenter.setHorizontalAlignment( SwingConstants.CENTER );

        tblDados.getColumnModel().getColumn( 0 ).setCellRenderer( cellCenter );
        tblDados.getColumnModel().getColumn( 2 ).setCellRenderer( cellCenter );
        tblDados.getColumnModel().getColumn( 3 ).setCellRenderer( cellCenter );
        tblDados.getColumnModel().getColumn( 4 ).setCellRenderer( cellRight );

        tblDados.getColumnModel().getColumn( 0 ).setPreferredWidth( 70 );
        tblDados.getColumnModel().getColumn( 1 ).setPreferredWidth( 350 );
        tblDados.getColumnModel().getColumn( 2 ).setPreferredWidth( 100 );
        tblDados.getColumnModel().getColumn( 3 ).setPreferredWidth( 80 );
        tblDados.getColumnModel().getColumn( 4 ).setPreferredWidth( 340 );

    }

    private Object[][] getDados( List<NotaCariocaModel> lista ) {
        Object[][] dados = new Object[lista.size()][];
        int i = 0;
        for ( NotaCariocaModel model : lista ) {
            dados[i] = new String[]{
                model.getNumeroBoleto(),
                model.getNome(),
                model.getDataPagamento(),
                model.getTotal(),
                model.getProtocolo()};
            i++;
        }
        return dados;
    }

    private void configCustomSize( int largura, int altura ) throws HeadlessException {
        this.setSize( largura, altura );
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds( ( tela.width - getSize().width ) / 2, ( tela.height - getSize().height ) / 2,
                getSize().width, getSize().height );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarLoteRps;
    private javax.swing.JButton btnListarRpsEnviados;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel plConteudo;
    private javax.swing.JPanel plDados;
    private javax.swing.JPanel pnlListarRpsEnviados;
    private javax.swing.JScrollPane splDados;
    private javax.swing.JTable tblDados;
    // End of variables declaration//GEN-END:variables

}
