/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PopupForm.java
 *
 * Created on 21/10/2010, 13:22:20
 */
package br.com.eugeniosolucoes.view.forms;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author eugenio
 */
public class PopupForm extends javax.swing.JDialog {

    private HyperlinkEvent referenciaLink;
    private String html;

    /** Creates new form FormPopup
     * @param parent
     * @param modal */
    public PopupForm(java.awt.Frame parent, boolean modal) {
        super(parent, BaseForm.SYSTEM_TITLE, modal);
        initComponents();
        //setEditor();
        configSize();
    }

    private void configSize() throws HeadlessException {
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((tela.width-getSize().width)/2, (tela.height-getSize().height)/2,
                getSize().width, getSize().height);
    }

    public PopupForm(java.awt.Frame parent, boolean modal, String html, int largura, int altura) {
        super(parent, BaseForm.SYSTEM_TITLE, modal);
        initComponents();
        this.html = html;
        //setEditor();
        this.epPopup.setText( this.html );
        configCustomSize(largura, altura);
    }
    
    public PopupForm(java.awt.Frame parent, boolean modal, String title, String html, int largura, int altura) {
        super(parent, title, modal);
        initComponents();
        this.html = html;
        //setEditor();
        this.epPopup.setText( this.html );
        configCustomSize(largura, altura);
    }

    private void configCustomSize( int largura, int altura ) throws HeadlessException {
        this.setSize(largura, altura);
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((tela.width-getSize().width)/2, (tela.height-getSize().height)/2,
                getSize().width, getSize().height);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        epPopup = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        epPopup.setEditable(false);
        epPopup.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        epPopup.setAutoscrolls(false);
        epPopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                epPopupMouseClicked(evt);
            }
        });
        epPopup.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                epPopupHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(epPopup);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void epPopupMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_epPopupMouseClicked
    {//GEN-HEADEREND:event_epPopupMouseClicked
        //verificaClickNoLink(evt);
    }//GEN-LAST:event_epPopupMouseClicked

    private void epPopupHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt)//GEN-FIRST:event_epPopupHyperlinkUpdate
    {//GEN-HEADEREND:event_epPopupHyperlinkUpdate
        referenciaLink = evt;
    }//GEN-LAST:event_epPopupHyperlinkUpdate

    private void verificaClickNoLink(java.awt.event.MouseEvent evtm)  {
        if ( evtm != null ) {
            if ( referenciaLink.getEventType() == HyperlinkEvent.EventType.ENTERED ) {
                try {
                    try {
                        Desktop.getDesktop().browse(referenciaLink.getURL().toURI());
                    }
                    catch ( URISyntaxException ex ) {
                        Logger.getLogger(PopupForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                catch ( IOException ex ) {
                    Logger.getLogger(PopupForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    private void setEditor() {
        epPopup.setContentType("text/html");
        epPopup.setEditable(false);
        java.net.URL helpURL = this.getClass().getResource(
                html);
        if ( helpURL != null ) {
            try {
                epPopup.setPage(helpURL);
            }
            catch ( IOException e ) {
                System.err.println("Falha na tentativa de acesso: " + helpURL);
            }
        }
        else {
            System.err.println("Não foi possível carregar o recurso!");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane epPopup;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
